### ISSUE TITLE
Call to undefined function HumanMade\SimpleSaml\is_plugin_active_for_network() on multisite

### ISSUE THREAD

**Issue by guequierre** [humanmade/wp-simple-saml#15]
Enabling it on a multisite servers gives the following error:
Fatal error: Uncaught Error: Call to undefined function HumanMade\SimpleSaml\is_plugin_active_for_network() in /var/www/html/wordpress/wp-content/plugins/wp-simple-saml/inc/namespace.php:682 Stack trace: #0 /var/www/html/wordpress/wp-content/plugins/wp-simple-saml/inc/admin/namespace.php(140): HumanMade\SimpleSaml\is_sso_enabled_network_wide() #1 /var/www/html/wordpress/wp-content/plugins/wp-simple-saml/inc/admin/namespace.php(370): HumanMade\SimpleSaml\Admin\get_sso_settings('sso_debug') #2 /var/www/html/wordpress/wp-includes/class-wp-hook.php(286): HumanMade\SimpleSaml\Admin\filter_forced_sso(false) #3 /var/www/html/wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters(false, Array) #4 /var/www/html/wordpress/wp-content/plugins/wp-simple-saml/inc/namespace.php(150): apply_filters('wpsimplesaml_fo...', false) #5 /var/www/html/wordpress/wp-includes/class-wp-hook.php(288): HumanMade\SimpleSaml\authenticate_with_sso(NULL) #6 /var/www/html/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array in /var/www/html/wordpress/wp-content/plugins/wp-simple-saml/inc/namespace.php on line 682

This can be fixed by including  ABSPATH . '/wp-admin/includes/plugin.php'.

This is documented in:
https://codex.wordpress.org/Function_Reference/is_plugin_active_for_network

Adding the piece of code above it fixed the issue for me.

**Comment by paulgibbs** [comment]
This issue was fixed very recently in #34. I'll tag a new release shortly.
