### ISSUE TITLE
Improve Composer file and Release on Packagist

### ISSUE THREAD

**Issue by mikeselander** [humanmade/wp-simple-saml#16]
While I can currently include this plugin using Composer installers, it would be really nice to be able to include it as a first-class Composer dependency. 

Will likely follow this up with a PR soon.

**Comment by spacedmonkey** [comment]
+1 on putting this on packagist.

**Comment by paulgibbs** [comment]
Anything blocking this? I think we just can.

**Comment by rmccue** [comment]
It's actually already up. https://packagist.org/packages/humanmade/wp-simple-saml
