### ISSUE TITLE
Upgrade PHP-SAML to v3.0

### ISSUE THREAD

**Issue by mikeselander** [humanmade/wp-simple-saml#17]
The PHP-SAML library currently uses the `mcrypt` library that was deprecated in PHP 7.1. This means that this plugin can't be used on WordPress VIP or, really, any modern web host. 

PHP-SAML has a 3.0 version which will could change some of the integration, but allows the plugin to be usable on modern hosts. It is not officially tagged, however it can be tagged with `3.0.0.x-dev` to at least prepare for the change.

Reference: https://github.com/onelogin/php-saml/issues/255

**Comment by mikeselander** [comment]
@shadyvb took a very early whack at including this updated library, but am noticing that part of the saml library is also stored in git - why is this setup that way if we're pulling it in with Composer? 

It would be nice to only use Composer for this dependency, but I assume that there's a reason for storing part of these files in git.

**Comment by spacedmonkey** [comment]
3.0.0 is now stable (see [this](https://github.com/onelogin/php-saml/releases/tag/v3.0.0)). This plugin should be updated to use version 3.0.0. 

Having a quick look at 3.0.0, it doesn't seem like it is a breaking change in it. So should be safe enough to upgrade. Hopefully it is a matter of upgrading it, and it is a drop-in solution to missing mcrypt library in PHP 7.2.
