### ISSUE TITLE
all sso/* paths lead to 404

### ISSUE THREAD

**Issue by tinder-kyleboss** [humanmade/wp-simple-saml#35]
I have successfully been able to set-up wp-simple-saml on several projects; however, I have a particular project where wp-simple-saml 404's on all sso routes (e.g. `sso/login`, `sso/verify`, & `sso/metadata`). Is there something that might be blocking the creation of these URLs?

Thank you so much!

**Comment by tinder-kyleboss** [comment]
I "fixed" my own issue 😅 I say _fixed_ fairly liberally lol. Here's why (If you run into the URLs not working...try this.)

1. De-activate `wp-simple-saml`.
2. Change [this line](https://github.com/humanmade/wp-simple-saml/blob/master/inc/namespace.php#L67) from `if ( ! get_option( 'wpsimplesaml_rr_flushed' ) ) {` to `if ( true ) ) {`.
3. Re-activate `wp-simple-saml`.
4. Undo step 2.

🤦‍♂️ 🤦‍♀️ 🤦‍♂️ 🤦‍♀️ 🤦‍♂️ 🤦‍♀️ 

I might have some free-time this weekend to look into a more permanent solution.

**Comment by paulgibbs** [comment]
@tinder-kyleboss That will cause WordPress to flush its permalink cache on every page load, which is slow and doesn't scale. That's what this option tried to improve, by only running the process once. I'm not sure why it might not have worked for you, but even the code comment says "not perfect but it should work at least the first time" so who knows? :)

Your WordPress needs to use a WordPress permalink option, other than the default. You've probably already got it customised, but you can set it on wp-admin > Settings > Permalinks. A good trick is just *visiting* the URL will also manually clear the permalink cache; you don't have to change or resave anything. I expect this would have resolved the issue for you (and you should be able to undo your modification once you have SSO working).
