### ISSUE TITLE
not even getting the configuration page

### ISSUE THREAD

**Issue by f1-outsourcing** [humanmade/wp-simple-saml#89]
How difficult can it be to make the configuration page show by default?

**Comment by rmccue** [comment]
Per [our support policy](https://engineering.hmn.md/projects/support/), we don't provide end-user support, and we expect that you debug issues yourself before reporting.

**Comment by rmccue** [comment]
You're welcome to not use it. We use it in production with millions of users connected, so it's not going anywhere.

**Comment by f1-outsourcing** [comment]
So you should make the repo private, now people waste their time on this.
